### ISSUE TITLE
Problems running example code

### ISSUE THREAD

**Issue by dholms** [paulmillr/noble-bls12-381#20]
I'm getting several different errors while running the example code from the README.

Environment: running locally in node.js on a lightweight express server.

```ts
  const privateKey = '67d53f170b908cabb9eb326c3c337762d59289a8fec79f7bc9254b584b73265c';
  const msg = 'hello';
  const publicKey = bls.getPublicKey(privateKey);
  const signature = await bls.sign(msg, privateKey);
  const isCorrect = await bls.verify(msg, publicKey, signature);
```
```
(node:6722) UnhandledPromiseRejectionWarning: Error: Expected hex string or Uint8Array, got 0hello
    at hexToBytes (/home/daniel/Projects/fission/fil-cosigner/node_modules/noble-bls12-381/index.js:74:19)
    at Function.hashToCurve (/home/daniel/Projects/fission/fil-cosigner/node_modules/noble-bls12-381/index.js:241:19)
...
```

Alrighty, no plaintext msgs. Let's convert the msg to a Uint8Array:
```ts
  const fromHexString = hexString =>
    new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));

  const privateKey = '67d53f170b908cabb9eb326c3c337762d59289a8fec79f7bc9254b584b73265c';
  const msg = fromHexString('hello');
  const publicKey = bls.getPublicKey(privateKey);
  const signature = await bls.sign(msg, privateKey);
  const isCorrect = await bls.verify(msg, publicKey, signature);
```
```
(node:8466) UnhandledPromiseRejectionWarning: Error: The given point is not on G1: y**2 = x**3 + b
    at Function.fromCompressedHex (/home/daniel/Projects/fission/fil-cosigner/node_modules/noble-bls12-381/index.js:187:19)
    at normP1 (/home/daniel/Projects/fission/fil-cosigner/node_modules/noble-bls12-381/index.js:323:55)
    at Object.verify (/home/daniel/Projects/fission/fil-cosigner/node_modules/noble-bls12-381/index.js:34
...
```
Everything works well up to `verify`. I also tried, hashing the msg to a point on G2 before `verify` which didn't change anything. This appears to be an issue with the public key, since the public key is supposed to be on G1. 

Any thoughts/ideas?

**Comment by paulmillr** [comment]
sorry for that -- i'm going to fix this now. The UX should have been better.

**Comment by dholms** [comment]
Thank you :pray:

**Comment by paulmillr** [comment]
fixed
